from . import animemory_node

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(animemory_node.NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(animemory_node.NODE_DISPLAY_NAME_MAPPINGS)

all = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]